spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 45000
        response-timeout: 45s
        pool:
          max-connections: 20
          type: FIXED
          max-idle-time: 600000ms
          eviction-interval: 120000ms
      routes:
        - id: my-service
          uri: lb://my-service
          predicates:
            - Path=/**


eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  server:
    port: 0